### ISSUE TITLE
Is the tutorial finished?

### ISSUE THREAD

**Issue by stavalfi** [yinonc/ES5-ES6-Default-Params#2]
> ## Default Arguments ES6:
> #### Default Variables:
> In ES6 we have a very readable syntax which allows us declaring default values for function’s arguments:
> ```  
> function multiply(a, b = 2) {
>     return a * b;
> }
> ```
>
> 
> ```  
> console.log(multiply(5));   // 10
> console.log(multiply(3,6)); // 18
> console.log(multiply());    // NaN
> ```
> Why is the third a NaN? Because we haven’t passed or set any value \ default value.  
> 
> Very simple ha? Let's get things a little more complicated! :)

I don't see the reason for `NaN` until the end of the tutorial. Am I missing something?

**Comment by yinonc** [comment]
When you're not passing any value, the calculate is `undefined * 2`, which is NaN.
